name: Difference CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
              java-version: 17

        - name: Run all unit tests
          run: ./gradlew allTests

        - name: Kotlin lint
          run: ./gradlew ktlintCheck
