name: Publish

on:
  release:
    types:
      - created

jobs:
    publish:
        runs-on: macos-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
              java-version: 17

        - name: Publish JVM, JS, Linux, and Apple libraries to Maven
          run: ./gradlew publishAllPublicationsToSonatypeRepository
          env:
              SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
              SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
              SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

    publish-windows:
        runs-on: windows-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Publish Windows x64 library to Maven
          run: ./gradlew publishMingwX64PublicationToSonatypeRepository
          env:
              SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
              SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
              SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
